# -*- coding: utf-8 -*-
"""Data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVF2oNUZE0B0x1OhxlzsRnb9rWcHNaPV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/sample_data/HRSEA Ramco Webinar_New_2.csv')
df.head(5)

# Calculate the value counts for 'location'
locationmetric = df['location'].value_counts()

# Calculate the value counts for 'Designation' and get the top 10
designationmetric = df['Desingation'].value_counts().head(10)

# Print the results
print(locationmetric)
print(designationmetric)

# Extract the 'Desingation' column
DesigVal = df['Desingation']

# Initialize counters for each category
vp_count = 0
hr_director_count = 0
head_count = 0

# Iterate through the 'Desingation' column and search for keywords
for designation in DesigVal:
    if pd.notna(designation):  # Ensure the value is not NaN
        # Check for VP or Vice President (case-insensitive)
        if "vp" in designation.lower() or "vice president" in designation.lower():
            vp_count += 1
        # Check for HR Director (case-insensitive)
        if "hr director" in designation.lower():
            hr_director_count += 1
        # Check for Head (case-insensitive)
        if "head" in designation.lower():
            head_count += 1

# Print the counts
print(f"Total number of VPs or Vice Presidents: {vp_count}")
print(f"Total number of HR Directors: {hr_director_count}")
print(f"Total number of Heads: {head_count}")

# -------- Horizontal Bar Graph for Location Metrics --------
plt.figure(figsize=(7, 6))
locationmetric.plot(kind='barh', color='skyblue')
plt.title('Location Distribution')
plt.xlabel('Count')
plt.ylabel('Location')
plt.tight_layout()
plt.show()

# -------- Vertical Bar Graph for VP, HR Director, and Head Counts with Value Labels --------
# Data for vertical bar chart
categories = ['VP or Vice President', 'HR Director', 'Head']
counts = [vp_count, hr_director_count, head_count]

plt.figure(figsize=(7, 6))
ax = sns.barplot(x=categories, y=counts, palette='viridis')

# Adding value labels on top of the bars
for i in ax.containers:
    ax.bar_label(i)

plt.title('Designation Counts')
plt.ylabel('Count')
plt.xlabel('Designation')
plt.tight_layout()
plt.show()